title: Jeffrey Tong
theme: just-the-docs

url: https://spiralsim.github.io/spiralsim.github.io

aux_links:
  LinkedIn: https://www.linkedin.com/in/jeffrey-w-tong/
  Goodreads: https://www.goodreads.com/user/show/183524223-jeffrey-tong
  GitHub: https://github.com/spiralsim

favicon_ico: "/assets/favicon.png"
