title: Jeffrey Tong
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  GitHub: https://github.com/spiralsim
  LinkedIn: https://www.linkedin.com/in/jeffrey-w-tong/
  Email: mailto:jeffrey.w.tong@gmail.com
  Instagram: https://www.instagram.com/jeffrey.w.tong
  Codeforces: https://codeforces.com/profile/spiralsim
  Goodreads: https://www.goodreads.com/user/show/183524223-jeffrey-tong

favicon_ico: "/assets/favicon.png"
