title: Jeffrey Tong
theme: just-the-docs

url: https://spiralsim.github.io/spiralsim.github.io

aux_links:
  GitHub: https://github.com/spiralsim
  LinkedIn: https://www.linkedin.com/in/jeffrey-w-tong/

favicon_ico: "/assets/favicon.png"
